audit_header: false
title: "Antelope Valley's Best Real Estate Training"
description: Rob Talbot, a top Real Estate Agent in Antelope Valley, shares his own internal real estate agent training for free. His Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: Events
    url: #
  - title: Free Strategy Call
    url: /contact/
client:
  name: Rob Talbot
  title:
  license_number:
  about_markdown: |
    I am an accomplished real estate professional with many years of working with buyers and sellers. This is more than a business to me… it is my mission to help my clients make educated decisions as they make one of the biggest investments of their lives. When you get ready to sell, I will provide a full market analysis allowing you to maximize the potential of your return, provide professional advice for staging your home and a marketing package that will assure you the information on your property is reaching the masses. I have lived in the Antelope Valley since 1984 and have been a successful business owner since 2003. In addition, I have been a recognized leader and innovator within community and charitable organizations, aggressive amongst competition and assertive while obtaining goals. I believe you will find me to be detail oriented, goal driven and dedicated to the continuation of personal and professional excellence in the Real Estate business.
  market: Antelope Valley
  brand: Keller Williams
  brokerage:
  address: 1401 West Rancho Vista Boulevard Suite B<br>Palmdale, CA 93551
  phone: 661-524-5151
  phone_type:
  phone2:
  phone2_type:
  email: robtalbot@kw.com
  url: https://www.avhousingmarket.com

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Looking to Build Your Real Estate Career?"
    CTA_text: "Let's talk about how Keller Williams can take your business to new heights."
    CTA_link_text: "Free Strategy Session"
    CTA_url: /contact/

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/002.jpg
#     CTA_title2: "Join Our Team"
#     CTA_text2: "Sell more homes by joining forces with the our dynamic real estate company."
#     CTA_link_text2: "Career Info"
#     CTA_url2: /

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: true
  facebook_url:
  linkedin_url: https://www.linkedin.com/in/rob-talbot-46893432/
  gplus_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/SoldByTalbot/
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Antelope Valley Real Estate Podcast with Rob Talbot'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Antelope Valley Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Keller Williams - your professional Antelope Valley Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Antelope Valley, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Rob Talbot'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Antelope Valley Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#b40101'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
